### ISSUE TITLE
ReSharper 2019.2 support

### ISSUE THREAD

**Issue by mareklinka** [ERNICommunity/AgentMulder#43]
R# 2019.2 will be landing soon (EAP 6 as of right now) and we need to migrate Mulder to the latest SDK.

**Comment by mareklinka** [comment]
Fixed by #44.

**Comment by Jawvig** [comment]
As of 2019-09-19 the 2019.2 support is still not available in the feed "https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v192.0/". Does anyone know what the impediment is (i.e. who can I chase)? In the meantime is there another feed we can add in the "Extension Manager" area of the ReSharper settings that will provide access to the latest version?

**Comment by mareklinka** [comment]
Right, sorry for this. I was doing some testing on the release, then I got distracted by a ton of work, then I simply forgot to hit the release build. I will try to get the current version out later today (CEST time).

**Comment by Jawvig** [comment]
Hey, thanks for this but please don't stress on it! Whenever is convenient.
